#!/bin/bash
#delete directories
#echo 'delete directiories'
rm -rf domains/ckks.edu.pl/public_nodejs/styles
rm -rf domains/ckks.edu.pl/public_nodejs/pages
rm -rf domains/ckks.edu.pl/public_nodejs/components
#rm -rf domains/ckks.edu.pl/public_nodejs/public
rm -rf domains/ckks.edu.pl/public_nodejs/.next
cd /domains/ckks.edu.pl/public_nodejs
ls


echo 'copy styles'
scp -P 22 -r -C /Users/miki/PhpstormProjects/ckks-nextjs/styles ckkspl@s42.mydevil.net:domains/ckks.edu.pl/public_nodejs

echo 'copy components'
scp -P 22 -r -C /Users/miki/PhpstormProjects/ckks-nextjs/components ckkspl@s42.mydevil.net:domains/ckks.edu.pl/public_nodejs

echo 'copy pages'
scp -P 22 -r -C /Users/miki/PhpstormProjects/ckks-nextjs/pages ckkspl@s42.mydevil.net:domains/ckks.edu.pl/public_nodejs

#echo 'copy  public folder'
#scp -P 22 -r -C /Users/miki/PhpstormProjects/ckks-nextjs/public ckkspl@s42.mydevil.net:domains/ckks.edu.pl/public_nodejs

echo 'copy .next folder'
scp -P 22 -r -C /Users/miki/PhpstormProjects/ckks-nextjs/.next ckkspl@s42.mydevil.net:domains/ckks.edu.pl/public_nodejs

echo 'restart server'
ssh ckkspl@s42.mydevil.net devil www restart ckks.edu.pl
